# Generated by Django 2.0.5 on 2018-08-30 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(default='Vehicle Service Station', max_length=100, null=True)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('A battery test checking', 'A battery test checking'), ('The tyres and their pressure', 'The tyres and their pressure'), ('Visual inspection of steering and suspension', 'Visual inspection of steering and suspension'), ('Check antifreeze/engine coolant', 'Check antifreeze/engine coolant'), ('Top up fluid levels and washers', 'Top up fluid levels and washers'), ('Check lights', 'Check lights')], max_length=174, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('fuel', models.CharField(max_length=25)),
            ],
        ),
    ]
