# Generated by Django 2.0.5 on 2018-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('autorickshaw', 'Autorickshaw')], default='car', max_length=255),
        ),
    ]
