# Generated by Django 2.0.5 on 2018-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_auto_20180729_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(max_length=25),
        ),
    ]
