# Generated by Django 2.0.5 on 2018-08-09 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_auto_20180809_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
