# Generated by Django 2.0.5 on 2018-08-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_auto_20180810_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
    ]
