# Generated by Django 2.0.5 on 2018-08-12 05:39

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_auto_20180812_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
