# Generated by Django 2.0.5 on 2018-08-12 05:57

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_shop_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
