# Generated by Django 2.0.5 on 2018-08-12 08:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_auto_20180812_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='position',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
