# Generated by Django 2.0.5 on 2018-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_auto_20180812_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(default=51.22222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='lon',
            field=models.FloatField(default=21.5555553),
            preserve_default=False,
        ),
    ]
