# Generated by Django 2.0.5 on 2018-08-15 13:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0014_auto_20180815_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='lon',
            new_name='long',
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
