# Generated by Django 2.0.5 on 2018-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0015_auto_20180815_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
