# Generated by Django 2.0.5 on 2018-08-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0016_nearbyshops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NearbyShops',
        ),
    ]
