# Generated by Django 2.0.5 on 2018-08-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0019_auto_20180822_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_vehicle',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
