# Generated by Django 2.0.5 on 2018-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0022_auto_20180822_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
