# Generated by Django 2.0.5 on 2018-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0023_shop_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
