# Generated by Django 2.0.5 on 2018-08-22 09:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0024_auto_20180822_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('battery test', 'A battery test checking'), ('tyre pressure', 'The tyres and their pressure'), ('steering and suspension', 'Visual inspection of steering and suspension'), ('engine coolant checking', 'Check antifreeze/engine coolant'), ('fluid levels', 'Top up fluid levels and washers'), ('check lights', 'Check lights')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(default='Vehicle Service Station', max_length=100, null=True),
        ),
    ]
