# Generated by Django 2.0.5 on 2018-08-22 09:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0026_auto_20180822_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A battery test checking', 'A battery test checking'), ('The tyres and their pressure', 'The tyres and their pressure'), ('Visual inspection of steering and suspension', 'Visual inspection of steering and suspension'), ('Check antifreeze/engine coolant', 'Check antifreeze/engine coolant'), ('Top up fluid levels and washers', 'Top up fluid levels and washers'), ('Check lights', 'Check lights')], max_length=174, null=True),
        ),
    ]
